server:
  port: 8080

spring:
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  #  Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/pose-management?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  #    MVC搜索路径
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #      模板校验关闭
  thymeleaf:
    check-template-location: false

files:
  upload:
    local:
      path: C:\Users\Administrator\Desktop\上传\
      maxFileSize: 104857600
    oss:
    #.....
    hadoop:
    #.....